# Generated by Django 4.2.7 on 2023-11-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_alter_empresa_groups_alter_empresa_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
        migrations.AlterModelManagers(
            name='empresa',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='password',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='username',
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa_groups',
            field=models.ManyToManyField(related_name='empresa_related_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa_user_permissions',
            field=models.ManyToManyField(related_name='empresa_related_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
