# Generated by Django 4.2.6 on 2023-11-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0003_categoria_rename_cnpj_empresa_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='duracao',
            field=models.IntegerField(null=True),
        ),
    ]
