# Generated by Django 4.2.7 on 2023-11-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0005_alter_list_comentario_alter_list_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtracaoCaracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('caracteristicas', models.ManyToManyField(to='destinos.atracaocaracteristica')),
            ],
        ),
    ]
