# Generated by Django 4.2.7 on 2023-11-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0003_delete_empresa'),
        ('destinos', '0007_remove_atracaocaracteristica_nome_and_more'),
    ]

    operations = [
    ]
