# Generated by Django 4.2.7 on 2023-11-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0008_merge_20231128_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('criacao_data', models.DateTimeField(auto_now_add=True)),
                ('delecao_data', models.DateTimeField(blank=True, null=True)),
                ('email_contato', models.EmailField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
    ]
