# Generated by Django 4.2.7 on 2023-11-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_empresa_user'),
        ('destinos', '0009_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='empresaid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa'),
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
